config/routes.rb
Rails.application.routes.draw do
  get 'welcomer/index'

  get 'welcomer/about'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcomer_controller.rb
class WelcomerController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcomer_helper.rb
module WelcomerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TurbolinksEvents</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

</head>
<body>

<%= yield %>

<script type="text/template" class="spinner-tpl">
    <div class="spinner-wrap">
        <div class="spinner">
            <span class="glyphicon glyphicon-refresh spinning"></span>
        </div>
    </div>
</script>
</body>
</html>

app/views/welcomer/about.html.erb
<h1>Welcomer#about</h1>
<p><%= link_to 'Home', welcomer_index_path %></p>
<p>Find me in app/views/welcomer/about.html.erb</p>

app/views/welcomer/index.html.erb
<h1>Welcomer#index</h1>

<p><%= link_to 'About', welcomer_about_path %></p>
<p>Find me in app/views/welcomer/index.html.erb</p>